### ISSUE TITLE
Responsive Design in screen 5.5 inch

### ISSUE THREAD

**Issue by montanojd** [snndmnsz/pawpaw#1]
Hello, congrats for a great script i have an issue with 5.5 inch device in android and iphone, is not responsive at the start screen
![image](https://user-images.githubusercontent.com/60124037/172077013-b31a4065-edff-4238-9767-0514c877fc0a.png)

**Comment by snndmnsz** [comment]
@montanojd  yes unfortunately I am aware of that, I used the Iphone 13 simulator while writing the code and it was on a 6 inch screen. For this reason, I did not consider screens with 5.5 inches and below. After solving some bugs (such as date selection problem etc.) in the app, I will try to make fixes on ui for small screens. If you want, you can try on a 6 inch(or higher) device, you will get more comfortable-clean interface. Thank you for feedback.

**Comment by montanojd** [comment]
Great, I wll definitely try with a higher inch device. Thanks.

**Comment by snndmnsz** [comment]
@montanojd  Hello, I have solved the responsive screen size problem that occurs on the start screens. The device I'm testing is the xperia z5 with 5.2 inch screen. You can now test the app on devices 6 inches and below. However, there may still be some responsive size problems in the internal screens. I didn't have time to test them all. It would be great if you see one and report it.

![imgonline-com-ua-twotoone-miVZW43urj0](https://user-images.githubusercontent.com/42818330/172723428-179797c8-90f4-4009-8b3b-1f24571ae4a0.jpg)
